- name: What's New
  description: Discover the latest product additions to the Singapore Government Developer Portal here
  items:
    - Overview
    - 'I2C {{Infra to Code}}'
    - Notarise
    - Secure Infrastructure-as-Code
    - Transcribe
    - TechBiz
    - Transcribe
    
- name: Data Science and Artificial Intelligence
  description: Access Data Science and Artificial Intelligence (DSAI) products developed by the Singapore Government, best practices and other resources here.
  items:
    - Overview
    - VAS
    - Analytics by Design
    - Data Literacy ePrimer

- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - Asynchronous Data Exchange
    - APEX
    - Cloud File Transfer
    - Container Stack
    - Corppass
    - DECADA IoT Tech Stack
    - Identiface
    - Login
    - Myinfo
    - Personalise
    - SHIP-HATS
    - Singapore Government Design System
    - Secure Infrastructure-as-Code
    - StackOps
    - TechBiz
    - Transcribe
    - VAS
    - Verify
    - WOGAA
