- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - Asynchronous Data Exchange
    - APEX
    - Cloud File Transfer
    - Container Stack
    - Government on Commercial Cloud
    - SHIP-HATS
    - StackOps
